#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

IP="8.8.8.8" 
COUNT=5
 
if ping -c $COUNT $IP > /dev/null 2>&1; then
  echo "Ping to $IP was successful."
else
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
